services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: exsearch_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
